### ISSUE TITLE
Output has different number of frames

### ISSUE THREAD

**Issue by mwalczyk** [LongguangWang/SOF-VSR#10]
Hi,

I noticed that when running SOF-VSR on an input frame sequence with N frames, the output has (N - 2) frames. It doesn't produce the first and last frames in the sequence. What is the best way to get around this limitation? Should we duplicate the first and last frames of the input sequence before running the model? Thanks!

**Comment by LongguangWang** [comment]
Sorry for the inconvenience.
Our network takes as input I_{t-1}, I_{t} and I_{t+1} to super-resolve I_{t}. Therefore, the first and last frames are not produced. You can duplicate the first and last frames of the input sequence before running the model, and the output could meet your needs.
