### ISSUE TITLE
About evaluation metric:T-MOVIE,MOVIE and VQM-VFD

### ISSUE THREAD

**Issue by duck9144** [LongguangWang/SOF-VSR#13]
Thank for your excellent work. It helps me a lot. I want to evaluate the consistency performance of my results . How do you implement these evaluation metrics:T-MOVIE, MOVIE and VQM-VFD? Is there source code package to use?

**Comment by LongguangWang** [comment]
Hi, please refer to [VQA](https://github.com/LongguangWang/Video-Quality-Assessment) and [MOVIE](https://github.com/XinyiYing/MOVIE).

**Comment by XinyiYing** [comment]
We have organized the Matlab code framework of Video Quality Assessment metric T-MOVIE and MOVIE. [code](https://github.com/XinyiYing/MOVIE)
Welcome to have a look and use our code.
