### ISSUE TITLE
系统找不到指定的路径

### ISSUE THREAD

**Issue by se11en** [LongguangWang/SOF-VSR#2]
首先感谢你的工作
今天下载以后，使用Pytorch 0.4.1，在cpu模式下运行

报错内容：
Traceback (most recent call last):
  File "demo_Vid4.py", line 53, in <module>
    main(cfg)
  File "demo_Vid4.py", line 48, in main
    os.mkdir('results/' + video_name)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'results/calendar'

使用管理员模式运行也不行，请问应该怎么处理呢

**Comment by LongguangWang** [comment]
感谢你关注我们的工作。
很抱歉之前上传代码的时候漏将results文件夹上传。请在根目录下新建一个results文件夹或者重新下载整个repo即可。
如有其它问题，欢迎再次联系。

**Comment by se11en** [comment]
THX A LOT
