### ISSUE TITLE
Is it possible to add chop_forward

### ISSUE THREAD

**Issue by ABDOELSHEMY** [LongguangWang/SOF-VSR#3]
Hi @LongguangWang 
i was wonder if it possible to add chop_forward to this great project to avoid run out of memory and Freezing the pc,i don't know if it even possible with this kind of Video Super-Resolution.
thank you

**Comment by LongguangWang** [comment]
Hi @ABDOELSHEMY 
I've just updated the code and added a memory-efficient mode when running on GPU. Please try it.

**Comment by ABDOELSHEMY** [comment]
unfortunately i can not try it because pytorch no longer support my old 650tiboost gpu, i think it is time to buy new gpu to use this amazing project as it Results Much better than (srgan sr) in my tests.
thank you very much guys for your time and effort you spent to make this stunning work
