### ISSUE TITLE
Will you release code for training ?

### ISSUE THREAD

**Issue by zllrunning** [LongguangWang/SOF-VSR#4]
Hi, @LongguangWang 
Thanks your excellent work!
Will you release code and dataset for training ?

**Comment by LongguangWang** [comment]
Sorry for the inconvenience.
I'm afraid I cannot release the dataset due to copyright issue. All the videos used for training are collected from CDVL database ( www.cdvl.org) and you can also download them from this website. 
We will release our code for training after recent DDL.

**Comment by zllrunning** [comment]
OK, thanks for your reply.
