### ISSUE TITLE
测试时，收尾会丢失

### ISSUE THREAD

**Issue by rjdCS** [LongguangWang/SOF-VSR#5]
非常感谢您的工作。

测试是不知道为什么会丢失掉第一个SR图和最后一个SR图。

非常感谢！

**Comment by LongguangWang** [comment]
感谢您关注我们的工作。
网络是以t-1,t,t+1三个时刻的图像作为输入，超分辨t时刻的图像，因此舍弃了第一帧和最后一帧。如果需要对第一帧和最后一帧进行超分辨，可以通过输入1,1,2时刻的图像对1时刻进行超分辨。

**Comment by rjdCS** [comment]
非常感谢！

本人就住在国防科大对面，希望能有机会参观贵实验室。

再次感谢！

**Comment by LongguangWang** [comment]
非常欢迎 : )
