### ISSUE TITLE
Issues with Memory Usage

### ISSUE THREAD

**Issue by mwalczyk** [LongguangWang/SOF-VSR#8]
Hi,

I'm trying to run SOF-VSR on a machine with 24gb VRAM and 64gb CPU RAM. 

In CPU-only mode, I'm running into issues running the model on input images with resolutions larger than HD (1920 x 1080). In GPU-only mode, I can't run the model on input images with resolutions greater than 960 pixels. 

Is this in-line with your research and findings? What input resolutions are possible with SOF-VSR? Or, is it only limited by the amount of hardware on your system? Thanks so much!

**Comment by LongguangWang** [comment]
Sorry for the inconvience.
In our paper, we test our model on Vid4 and DAVIS-10. For 4x SR, we first downsample HR images (e.g., “calendar” in Vid4 with resolution of 720x576) to produce LR images (180x144). Then, our SOF-VSR takes the LR images (180x144) as input to generate the SR results (720x576). 
The resolution of input images that can be processed by our SOF-VSR depends on the hardware resource. If you want to super-resolve input images with high resolutions in a memory-efficient way, you can extract overlapped patches and feed them to the network separately.
