### ISSUE TITLE
Availability of training data?

### ISSUE THREAD

**Issue by mwalczyk** [LongguangWang/SOF-VSR#9]
Hi, 

Is the data that was used for training hosted anywhere?

I understand that the data was taken from https://www.cdvl.org/, but which videos were used?

**Comment by LongguangWang** [comment]
Sorry for the inconvenience.
Due to the copyright issue, we cannot release the training data.
We search for videos with 1080p resolution and download them except repeated ones. Then we manually extract 145 video clips from them.
